# Generated by Django 4.0.4 on 2022-10-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
    ]
