stages:
  - deploy
variables:
  GIT_STRATEGY: none
  BUILD_DIR : "angular-django-ecommerce"
  FRONT_DIR : "angular-ecommerce"
  BACK_DIR : "django-ecommerce"
deploy-job:
  stage: deploy  
  environment: production
  script:
    - cd /home/ubuntu/"$BUILD_DIR"/
    - sudo git config --global --add safe.directory /home/ubuntu/angular-django-ecommerce
    - sudo git pull
    - cd /home/ubuntu/"$BUILD_DIR"/"$BACK_DIR"/
    - source env/bin/activate
    - sudo python3 manage.py makemigrations
    - sudo python3 manage.py migrate
    - sudo python3 manage.py collectstatic --noinput
    - cd /home/ubuntu/projects/"$BUILD_DIR"/"$FRONT_DIR"/
    - sudo npm install --legacy-peer-deps
    - sudo npm run build --prod
    - sudo systemctl restart gunicorn
    - sudo systemctl restart nginx


